# fly.toml app configuration file generated for gnocal-labs on 2025-06-06T12:41:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gnocal-labs'
primary_region = 'dfw'

[build]
[build.args]
GO_VERSION = '1.24.3'

[env]
PORT = '8080'
GNOCAL__GNOLAND_RPC_URL = 'tcp://labsnet.internal:26657'
GNOCAL__SERVER_ADDRESS = '0.0.0.0:8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
