services:
  gnodev-labs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888" # Main API port
      - "26657:26657" # RPC interface
    volumes:
      # For local package development - map your local directories to container
      # If you want the ability to hot-reload inside of the container, add your labs based namespace here
      - ./gno.land/p/eve000:/gnoroot/examples/gno.land/p/eve000
      - ./gno.land/r/linker000:/gnoroot/examples/gno.land/r/linker000
      - ./gno.land/r/buidlthefuture000:/gnoroot/examples/gno.land/r/buidlthefuture000
      - ./gno.land/r/labs000:/gnoroot/examples/gno.land/r/labs000
    environment:
      - GNO_HOME=/gnoroot
    command: ["dev"]

    # Optional healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5
