# fly.toml app configuration file generated for labsnet on 2025-05-09T17:44:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'labsnet'
primary_region = 'dfw'

[build]

[http_service]
internal_port = 8888
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
processes = ['app']

[processes]
app = "-v -chain-id labs01 -web-listener 0.0.0.0:8888 -node-rpc-listener 0.0.0.0:26657 -balance-file /gnoroot/gno.land/genesis/genesis_balances.txt"

[[services]]
processes = ["app"]
http_checks = []
internal_port = 26657
protocol = "tcp"
script_checks = []

[[services.ports]]
port = 26657
handlers = ["tls"]

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
