# fly.toml app configuration file generated for labsnet on 2025-05-09T17:44:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'labsnet'
primary_region = 'dfw'

[env]
GNO_HOME = '/gnoroot'

[build]

[http_service]
internal_port = 8889
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
processes = ['app']

[processes]
app = "staging"

[[services]]
processes = ["app"]
http_checks = []
internal_port = 26657
protocol = "tcp"
script_checks = []

[[services.ports]]
port = 8443
handlers = ["tls"]

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2
