# fly.toml app configuration file generated for gnolinker-discord-stg on 2025-07-09T08:31:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gnolinker-discord-stg'
primary_region = 'dfw'

[env]
GNOLINKER__GNOLAND_RPC_ENDPOINT = 'https://aiblabs.net:8443'
GNOLINKER__BASE_URL = 'https://aiblabs.net'
AWS_ENDPOINT_URL_S3 = 'https://fly.storage.tigris.dev'
AWS_REGION = 'auto'
GNOLINKER__STORAGE_TYPE = 's3'
GNOLINKER__LOCK_TYPE = 's3'
GNOLINKER__LOCK_DEFAULT_TTL = '10s'


GNOLINKER__LOG_LEVEL = 'debug'
[build]

[processes]
app = 'discord'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
